### ISSUE TITLE
Update AppLovin SKAdNetwork ID endpoint

### ISSUE THREAD

**Issue by thomasmso** [ChartBoost/chartboost-mediation-unity-sdk#216]
We're deprecating the endpoint that you currently have defined in `SKAdNetworkConstants.cs`:

https://github.com/ChartBoost/chartboost-mediation-unity-sdk/blob/bd250636a8411e9fdeca602f89d452b03284a4b8/com.chartboost.mediation/Editor/SKAdNetwork/SKAdNetworkConstants.cs#L5

Please update to https://skadnetwork-ids.applovin.com/v1/skadnetworkids.json.

**Comment by SCastanedaMunoz** [comment]
@thomasmso Thanks for letting us know, I will make not of it and fix it for the next release.

**Comment by SCastanedaMunoz** [comment]
@thomasmso A Pull Request has been merged into our internal development repo and this will be available in our next release. I will close this issue now 👍🏻
