### ISSUE TITLE
Chartboost mediation for Amazon FireTV

### ISSUE THREAD

**Issue by geeks-eng** [ChartBoost/chartboost-mediation-unity-sdk#220]
One of the apps I saw on FireTV was displaying Chartboost full-screen advertisement. Can I add Chartboost mediation to my FireTV game developed in Unity using this mediation SDK? Since it is a mediation SDK which main network will I have to use for the mediation?

**Comment by pleasesavemycat** [comment]
Going to be honest here, we never tried testing it with a FireTV. It should technically work without issue since FireTV is basically Android and the Mediation SDKs work for Fire tablets without issue.
